### ISSUE TITLE
french number not detected as french

### ISSUE THREAD

**Issue by FrColin** [thomasthiebaud/spacy-fastlang#11]
french word for number are not detected as 'fr' language
small test program below  yield result:

**Text: ceci est du francais LANG: fr SCORE: 0.8692260980606079
Text: donnez quarante cinq cinquante euros LANG: xx SCORE: 0.44422411918640137
Text: donnez 45 50 euros LANG: en SCORE: 0.20330046117305756**

```
import spacy
import spacy_fastlang
nlp_lang = spacy.blank('xx')
nlp_lang.add_pipe('language_detector', config={"supported_languages": ["fr","en"]})

texts = ["ceci est du francais","donnez quarante cinq cinquante euros", "donnez 45 50 euros"]

for t in texts:
    doc = nlp_lang(t)
    print( "Text: {} LANG: {} SCORE: {}".format( t, doc._.language, doc._.language_score))
```

**Comment by thomasthiebaud** [comment]
You're right, but it is likely coming from the model itself rather than the library. Here are the top 3 languages detected for your examples

```
[('__label__fr', 0.8692260980606079), ('__label__la', 0.07981850951910019), ('__label__vi', 0.015786711126565933)]
Text: ceci est du francais LANG: fr SCORE: 0.8692260980606079
[('__label__it', 0.44422411918640137), ('__label__fr', 0.2902344763278961), ('__label__en', 0.05172138288617134)]
Text: donnez quarante cinq cinquante euros LANG: xx SCORE: 0.44422411918640137
[('__label__en', 0.20330046117305756), ('__label__it', 0.14236119389533997), ('__label__fr', 0.10877827554941177)]
Text: donnez 45 50 euros LANG: en SCORE: 0.20330046117305756
```

You have a couple of options:
- provide your own model using `model_path`
- add a `threshold`, so it falls back to `xx` (or something else) if the confidence is too low

**Comment by FrColin** [comment]
Thank you for your help , I slove the problem with a bigger model found on fasttest [lid.176.bin](https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin),
seem to be the same version of the lid.176.ftz but uncompressed.

**Comment by thomasthiebaud** [comment]
Glad to hear you found a solution. Yes, the bigger version is supposed to be more accurate, but it feels too big to be shipped by default in this project.

I'll close the issue for now.
