### ISSUE TITLE
Not good at detecting english?

### ISSUE THREAD

**Issue by KastanDay** [thomasthiebaud/spacy-fastlang#13]
Hi, I tried this against youtube transcripts generated by Whisper, and I found that it doesn't do a good job of predicting english.

Is this expected behavior? Is it better at some languages than others? 

Thanks for any help, Kastan

<img width="1274" alt="CleanShot 2022-11-16 at 21 02 37" src="https://user-images.githubusercontent.com/13607221/202344668-0f6ddf59-c23f-4f34-a046-3796fcce44ca.png">

**Comment by KastanDay** [comment]
also yes, this is a rickroll. but also true.

**Comment by thomasthiebaud** [comment]
It does not look right indeed. I don't think I can do much here. My library just wraps a [fasttext model](https://fasttext.cc/docs/en/language-identification.html) to be used with Spacy. The library is not responsible for the predictions.

It does look like that the predictions are correct with lower cased sentences. Maybe you could add that as a preprocessing step on your end
