### ISSUE TITLE
Lower spacy version requirements

### ISSUE THREAD

**Issue by ruben-dedoncker** [thomasthiebaud/spacy-fastlang#15]
Currently the required spaCy version is set to 3.6.0 or higher. However, AFAIK the `LanguageDetector` does not use any spaCy features specific to that version  so the version constraint can safely be relaxed to a lower version (probably >= 3.0.0)

I personally tried it with spaCy 3.4.4 and it worked without any issues

**Comment by thomasthiebaud** [comment]
Thanks for opening and sorry for the delays to answer. I just released a version [2.1.0](https://pypi.org/project/spacy_fastlang/) that lowers the requirements on Spacy
