### ISSUE TITLE
Error when installing spacy_fastlang

### ISSUE THREAD

**Issue by D-i-l-r-u-k-s-h-i** [thomasthiebaud/spacy-fastlang#7]
Hi, 
source: [https://spacy.io/universe/project/spacy_fastlang](url)
This is what I entered in the Google Colab notebook but I get the following error

`!pip install spacy_fastlang`

`ERROR: Could not find a version that satisfies the requirement spacy_fastlang (from versions: none)
ERROR: No matching distribution found for spacy_fastlang`

How can I fi this? Thank you.

**Comment by thomasthiebaud** [comment]
Thanks for reporting the issue. Version `0.4.2` (PR #8 ) fixes that problem 
<img width="1631" alt="Screenshot 2020-06-22 at 07 33 57" src="https://user-images.githubusercontent.com/3715715/85251889-d150a100-b45a-11ea-83b2-8f934b8de482.png">
